name: Flutter App Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Appium Test
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '18'
        - name: Set up Node.js  
          uses: actions/setup-node@v3
          with:
            node-version: 20.5.0
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3
        - name: Check ADB
          run: adb version
        - name: Install dependencies
          run: npm install
        - name: Run Android Emulator
          run: |
            echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-28;google_apis;x86_64'
            echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test_device -k 'system-images;android-28;google_apis;x86_64' --force
            $ANDROID_HOME/emulator/emulator -list-avds
            echo "Starting emulator"
            nohup $ANDROID_HOME/emulator/emulator -avd test_device -no-snapshot > /dev/null 2>&1 &
            $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
            $ANDROID_HOME/platform-tools/adb devices
            echo "Emulator started"
        - name: Run Test
          run: npx wdio wdio.android.conf.ts --spec test/specs/*.ts
        - uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs
